CREATE TABLE patients
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    phone       VARCHAR(255)                            NOT NULL,
    active      BOOLEAN,
    document    VARCHAR(13)                             NOT NULL,
    country     VARCHAR(255),
    state       VARCHAR(255),
    city        VARCHAR(255),
    street      VARCHAR(255),
    postal_code VARCHAR(255),
    number      VARCHAR(255),
    complement  VARCHAR(255),
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

ALTER TABLE doctors
    ADD CONSTRAINT uc_doctors_phone UNIQUE (phone);

ALTER TABLE patients
    ADD CONSTRAINT uc_patients_document UNIQUE (document);

ALTER TABLE patients
    ADD CONSTRAINT uc_patients_email UNIQUE (email);

ALTER TABLE patients
    ADD CONSTRAINT uc_patients_phone UNIQUE (phone);