CREATE TABLE appointment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    doctor_id  BIGINT,
    patient_id BIGINT,
    date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_appointment PRIMARY KEY (id)
);

ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES doctors (id);

ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patients (id);