CREATE TABLE doctors
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    specialty      VARCHAR(50)  NOT NULL,
    phone          VARCHAR(255),
    license_number VARCHAR(255) NOT NULL,
    country        VARCHAR(255),
    state          VARCHAR(255),
    city           VARCHAR(255),
    street         VARCHAR(255),
    postal_code    VARCHAR(255),
    number         VARCHAR(255),
    complement     VARCHAR(255),
    CONSTRAINT pk_doctors PRIMARY KEY (id),
    CONSTRAINT uk_doctors_email UNIQUE (email),
    CONSTRAINT uk_doctors_license_number UNIQUE (license_number)
);
